<a href="https://colab.research.google.com/github/Krishishah7/nlp-learning-series/blob/main/03_search/search_query_type_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Query Type Analysis in Semantic Search

## Objective
This notebook analyzes how semantic search behaves across
different types of queries to understand retrieval robustness.

The goal is to observe how similarity scores and rankings
change depending on query intent and phrasing.

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
documents = [
    "Machine learning tutorials for beginners",
    "Deep learning and neural networks explained",
    "Natural language processing using transformers",
    "Python programming fundamentals",
    "Football match highlights",
    "Top travel destinations"
]

In [ ]:
queries = {
    "Informational": "learn machine learning basics",
    "Conceptual": "what is deep learning",
    "Programming": "python machine learning tutorial",
    "Unrelated": "best football players"
}

In [7]:
doc_embs = model.encode(documents)

results = []

for query_type, query in queries.items():

    query_emb = model.encode(query)
    scores = cosine_similarity([query_emb], doc_embs)[0]

    for doc, score in zip(documents, scores):
        results.append({
            "Query Type": query_type,
            "Query": query,
            "Document": doc,
            "Similarity Score": round(score, 4)
        })

df = pd.DataFrame(results)
df

,Query Type,Query,Document,Similarity Score
0,Informational,learn machine learning basics,Machine learning tutorials for beginners,0.8806
1,Informational,learn machine learning basics,Deep learning and neural networks explained,0.5321
2,Informational,learn machine learning basics,Natural language processing using transformers,0.2195
3,Informational,learn machine learning basics,Python programming fundamentals,0.3898
4,Informational,learn machine learning basics,Football match highlights,0.0823
5,Informational,learn machine learning basics,Top travel destinations,0.0293
6,Conceptual,what is deep learning,Machine learning tutorials for beginners,0.3159
7,Conceptual,what is deep learning,Deep learning and neural networks explained,0.7450
8,Conceptual,what is deep learning,Natural language processing using transformers,0.1702
9,Conceptual,what is deep learning,Python programming fundamentals,0.1365
10,Conceptual,what is deep learning,Football match highlights,-0.0246
11,Conceptual,what is deep learning,Top travel destinations,-0.0045
12,Programming,python machine learning tutorial,Machine learning tutorials for beginners,0.8184
13,Programming,python machine learning tutorial,Deep learning and neural networks explained,0.3718
14,Programming,python machine learning tutorial,Natural language processing using transformers,0.1827
15,Programming,python machine learning tutorial,Python programming fundamentals,0.5861
16,Programming,python machine learning tutorial,Football match highlights,0.0602
17,Programming,python machine learning tutorial,Top travel destinations,-0.0225
18,Unrelated,best football players,Machine learning tutorials for beginners,-0.0017
19,Unrelated,best football players,Deep learning and neural networks explained,0.0044
20,Unrelated,best football players,Natural language processing using transformers,0.0383
21,Unrelated,best football players,Python programming fundamentals,-0.0185
22,Unrelated,best football players,Football match highlights,0.2892
23,Unrelated,best football players,Top travel destinations,0.1728

In [8]:
df_sorted = df.sort_values(
    ["Query Type", "Similarity Score"],
    ascending=[True, False]
)

df_sorted

,Query Type,Query,Document,Similarity Score
7,Conceptual,what is deep learning,Deep learning and neural networks explained,0.7450
6,Conceptual,what is deep learning,Machine learning tutorials for beginners,0.3159
8,Conceptual,what is deep learning,Natural language processing using transformers,0.1702
9,Conceptual,what is deep learning,Python programming fundamentals,0.1365
11,Conceptual,what is deep learning,Top travel destinations,-0.0045
10,Conceptual,what is deep learning,Football match highlights,-0.0246
0,Informational,learn machine learning basics,Machine learning tutorials for beginners,0.8806
1,Informational,learn machine learning basics,Deep learning and neural networks explained,0.5321
3,Informational,learn machine learning basics,Python programming fundamentals,0.3898
2,Informational,learn machine learning basics,Natural language processing using transformers,0.2195
4,Informational,learn machine learning basics,Football match highlights,0.0823
5,Informational,learn machine learning basics,Top travel destinations,0.0293
12,Programming,python machine learning tutorial,Machine learning tutorials for beginners,0.8184
15,Programming,python machine learning tutorial,Python programming fundamentals,0.5861
13,Programming,python machine learning tutorial,Deep learning and neural networks explained,0.3718
14,Programming,python machine learning tutorial,Natural language processing using transformers,0.1827
16,Programming,python machine learning tutorial,Football match highlights,0.0602
17,Programming,python machine learning tutorial,Top travel destinations,-0.0225
22,Unrelated,best football players,Football match highlights,0.2892
23,Unrelated,best football players,Top travel destinations,0.1728
20,Unrelated,best football players,Natural language processing using transformers,0.0383
19,Unrelated,best football players,Deep learning and neural networks explained,0.0044
18,Unrelated,best football players,Machine learning tutorials for beginners,-0.0017
21,Unrelated,best football players,Python programming fundamentals,-0.0185

## Observations

- Informational queries retrieve tutorial-style documents effectively
- Conceptual queries retrieve explanation-style documents
- Programming queries prioritize coding-related documents
- Unrelated queries correctly retrieve non-NLP content

## Key Insight
Semantic search behavior depends strongly on query intent,
highlighting the importance of query understanding in
retrieval systems.