<a href="https://colab.research.google.com/github/Krishishah7/nlp-learning-series/blob/main/03_search/search_with_confidence_threshold_and_fallback.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semantic Search with Confidence Threshold and Fallback

## Objective
This notebook demonstrates how to add confidence-based decision logic
to a semantic search system by analyzing similarity scores and
introducing fallback behavior when confidence is low.

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
query = "learn machine learning basics"

documents = [
    "Machine learning tutorials for beginners",
    "Introduction to deep learning",
    "Python programming fundamentals",
    "Natural language processing with transformers",
    "Top travel destinations in summer",
    "Football match highlights"
]

In [8]:
query_emb = model.encode(query)
doc_embs = model.encode(documents)

scores = cosine_similarity([query_emb], doc_embs)[0]

df = pd.DataFrame({
    "Document": documents,
    "Similarity Score": np.round(scores, 4)
}).sort_values(by="Similarity Score", ascending=False)

df

                                        Document  Similarity Score
0       Machine learning tutorials for beginners            0.8806
1                  Introduction to deep learning            0.5455
2                Python programming fundamentals            0.3898
3  Natural language processing with transformers            0.2065
5                      Football match highlights            0.0823
4              Top travel destinations in summer            0.0231

In [9]:
top_score = df.iloc[0]["Similarity Score"]
second_score = df.iloc[1]["Similarity Score"]
score_gap = top_score - second_score

confidence_threshold = 0.15  # heuristic

confidence = "High" if score_gap >= confidence_threshold else "Low"

top_score, second_score, score_gap, confidence

(np.float32(0.8806), np.float32(0.5455), np.float32(0.3351), 'High')

In [10]:
if confidence == "High":
    result = df.head(3)
else:
    result = "Low confidence in search results. Ask user for clarification."

result

                                   Document  Similarity Score
0  Machine learning tutorials for beginners            0.8806
1             Introduction to deep learning            0.5455
2           Python programming fundamentals            0.3898

## Observations

- Score gaps provide a simple confidence signal
- Not all queries deserve a confident answer
- Fallback strategies reduce incorrect or misleading results

## Key Insight
Semantic search systems should evaluate confidence before
presenting results, especially in user-facing or RAG systems.