<a href="https://colab.research.google.com/github/Krishishah7/nlp-learning-series/blob/main/03_search/search_pipeline_summary_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# End-to-End Semantic Search Pipeline Demo

## Objective
This notebook demonstrates a complete semantic search pipeline
including embedding generation, similarity computation,
document ranking, and confidence evaluation.

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
documents = [
    "Machine learning tutorials for beginners",
    "Deep learning and neural networks explained",
    "Natural language processing with transformers",
    "Python programming fundamentals",
    "Football match highlights",
    "Top travel destinations"
]

In [ ]:
query = "learn machine learning basics"

In [ ]:
query_emb = model.encode(query)
doc_embs = model.encode(documents)

In [ ]:
scores = cosine_similarity([query_emb], doc_embs)[0]

In [10]:
df = pd.DataFrame({
    "Document": documents,
    "Similarity Score": np.round(scores,4)
}).sort_values(by="Similarity Score", ascending=False)

df

                                        Document  Similarity Score
0       Machine learning tutorials for beginners            0.8806
1    Deep learning and neural networks explained            0.5321
3                Python programming fundamentals            0.3898
2  Natural language processing with transformers            0.2065
4                      Football match highlights            0.0823
5                        Top travel destinations            0.0293

In [11]:
top_k = 3
top_results = df.head(top_k)

top_results

                                      Document  Similarity Score
0     Machine learning tutorials for beginners            0.8806
1  Deep learning and neural networks explained            0.5321
3              Python programming fundamentals            0.3898

In [12]:
top_score = df.iloc[0]["Similarity Score"]
second_score = df.iloc[1]["Similarity Score"]

score_gap = top_score - second_score

confidence = "High" if score_gap > 0.15 else "Low"

print("Confidence:", confidence)

Confidence: High

## Observations

The pipeline demonstrates how semantic search retrieves and ranks
documents based on meaning rather than keyword matching.

Confidence estimation helps determine whether the system is
certain about the top result.