<a href="https://colab.research.google.com/github/Krishishah7/nlp-learning-series/blob/main/01_embeddings/embedding_similarity_score_behavior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [ ]:
# Fixed model for controlled experiment
model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
sentence_pairs = [
    # Identical / Near-identical
    ("Machine learning is powerful", "Machine learning is powerful", "Identical"),
    ("Natural language processing is fun",
     "Natural language processing is fun", "Identical"),

    # Paraphrases
    ("I love studying machine learning",
     "I enjoy learning about machine learning", "Paraphrase"),
    ("She is building NLP systems",
     "She works on natural language processing projects", "Paraphrase"),

    # Topically related
    ("Transformers generate embeddings",
     "Sentence embeddings are used in semantic search", "Related"),
    ("Machine learning improves NLP tasks",
     "Natural language processing uses artificial intelligence", "Related"),

    # Unrelated
    ("I love machine learning",
     "The weather is very hot today", "Unrelated"),
    ("He plays cricket on weekends",
     "Sentence transformers create embeddings", "Unrelated")
]

In [7]:
results = []

for sent_a, sent_b, category in sentence_pairs:
    emb_a = model.encode(sent_a)
    emb_b = model.encode(sent_b)

    score = cosine_similarity([emb_a], [emb_b])[0][0]

    results.append({
        "Sentence A": sent_a,
        "Sentence B": sent_b,
        "Category": category,
        "Cosine Similarity": round(score, 4)
    })

df = pd.DataFrame(results)
df

,Sentence A,Sentence B,Category,Cosine Similarity
0,Machine learning is powerful,Machine learning is powerful,Identical,1.0000
1,Natural language processing is fun,Natural language processing is fun,Identical,1.0000
2,I love studying machine learning,I enjoy learning about machine learning,Paraphrase,0.8892
3,She is building NLP systems,She works on natural language processing projects,Paraphrase,0.7768
4,Transformers generate embeddings,Sentence embeddings are used in semantic search,Related,0.3823
5,Machine learning improves NLP tasks,Natural language processing uses artificial in...,Related,0.5731
6,I love machine learning,The weather is very hot today,Unrelated,0.0240
7,He plays cricket on weekends,Sentence transformers create embeddings,Unrelated,0.0039

In [8]:
df.groupby("Category")["Cosine Similarity"].agg(
    ["min", "max", "mean"]
).round(4)

               min     max    mean
Category
Identical   1.0000  1.0000  1.0000
Paraphrase  0.7768  0.8892  0.8330
Related     0.3823  0.5731  0.4777
Unrelated   0.0039  0.0240  0.0140